/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Whether the first admin profile still needs creating */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SetupStatus'];
          };
        };
      };
    };
    put?: never;
    /** Create the first admin profile and log it in */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SetupRequestInput'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LoginResponse'];
          };
        };
        /** @description Default Response */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/profiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profiles to pick from on the login screen */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Profile'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a profile id and PIN for a bearer token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequestInput'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LoginResponse'];
          };
        };
        /** @description Default Response */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Default Response */
        423: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Default Response */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The profile behind the current token */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Profile'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devices logged in to this profile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Session'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Log out another device */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Opaque identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/libraries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List libraries */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Library'][];
          };
        };
      };
    };
    put?: never;
    /** Create a library (admin) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateLibraryRequestInput'];
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Library'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/libraries/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a library */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Opaque identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Library'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a library and everything indexed from it (admin) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Opaque identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/libraries/{id}/scan': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Scan a library now (admin). Runs to completion before responding. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Opaque identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ScanStatus'];
          };
        };
        /** @description Default Response */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Browse or search items
     * @description Without kind or parentId, lists movies and shows. With parentId set to a show, lists its seasons and season-less episodes; set to a season, lists its episodes.
     */
    get: {
      parameters: {
        query?: {
          libraryKind?: components['schemas']['LibraryKindInput'];
          kind?: components['schemas']['ItemKindInput'];
          /** @description Opaque identifier */
          parentId?: string;
          search?: string;
          needsReview?: boolean;
          sort?: 'title' | 'year' | 'added' | 'lastPlayed';
          offset?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items: components['schemas']['ItemSummary'][];
              total: number;
              offset: number;
              limit: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/items/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Item detail with files, streams, and children */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Opaque identifier */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ItemDetail'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    LibraryKindInput: 'movie' | 'tv' | 'anime';
    /** @enum {string} */
    ItemKindInput: 'movie' | 'show' | 'season' | 'episode';
    ErrorResponseInput: {
      statusCode: number;
      error: string;
      message: string;
    };
    ProfileInput: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      isAdmin: boolean;
      avatarColor: string;
    };
    /** @description True until the first admin profile exists */
    SetupStatusInput: {
      needsSetup: boolean;
    };
    SetupRequestInput: {
      name: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
    };
    LoginRequestInput: {
      /** @description Opaque identifier */
      profileId: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
      deviceName: string;
    };
    LoginResponseInput: {
      token: string;
      profile: components['schemas']['ProfileInput'];
    };
    SessionInput: {
      /** @description Opaque identifier */
      id: string;
      deviceName: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      lastSeenAt: string;
      current: boolean;
    };
    LibraryInput: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      kind: components['schemas']['LibraryKindInput'];
      paths: string[];
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      lastScannedAt: string | null;
    };
    CreateLibraryRequestInput: {
      name: string;
      kind: components['schemas']['LibraryKindInput'];
      paths: string[];
    };
    ScanStatusInput: {
      /** @description Opaque identifier */
      libraryId: string;
      /** @enum {string} */
      state: 'idle' | 'running';
      filesSeen: number;
      filesChanged: number;
      filesMissing: number;
      filesProbed: number;
      /** @description Files ffprobe could not read */
      filesFailed: number;
      /** @description Files linked to a movie or episode this scan */
      itemsLinked: number;
      startedAt: string | null;
    };
    ProgressStateInput: {
      positionMs: number;
      durationMs: number;
      watched: boolean;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      updatedAt: string;
    };
    ItemSummaryInput: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKindInput'];
      libraryKind: components['schemas']['LibraryKindInput'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressStateInput'] | null;
    };
    StreamInfoInput: {
      index: number;
      /** @enum {string} */
      type: 'video' | 'audio' | 'subtitle';
      codec: string;
      language: string | null;
      title: string | null;
      isDefault: boolean;
      isForced: boolean;
      width: number | null;
      height: number | null;
      channels: number | null;
    };
    MediaFileInput: {
      /** @description Opaque identifier */
      id: string;
      fileName: string;
      sizeBytes: number;
      container: string;
      durationMs: number;
      bitrate: number | null;
      streams: components['schemas']['StreamInfoInput'][];
    };
    ItemDetailInput: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKindInput'];
      libraryKind: components['schemas']['LibraryKindInput'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressStateInput'] | null;
      overview: string | null;
      tagline: string | null;
      genres: string[];
      rating: number | null;
      airDate: string | null;
      runtimeMs: number | null;
      tmdbId: number | null;
      anilistId: number | null;
      files: components['schemas']['MediaFileInput'][];
      /** @description Seasons of a show, episodes of a season */
      children: components['schemas']['ItemSummaryInput'][];
    };
    FixMatchRequestInput: {
      tmdbId?: number;
      anilistId?: number;
      /** @description Anime only: shift when mapping absolute episodes onto TMDB seasons */
      seasonOffset?: number;
    };
    DeviceProfileInput: {
      name: string;
      /** @description e.g. mp4, mkv, webm */
      containers: string[];
      /** @description e.g. h264, hevc, vp9, av1 */
      videoCodecs: string[];
      /** @description e.g. aac, ac3, eac3, opus, flac */
      audioCodecs: string[];
      maxWidth: number | null;
      /** @description bits per second */
      maxBitrate: number | null;
      /** @enum {string} */
      hlsSegmentContainer: 'ts' | 'fmp4';
    };
    PlaybackDecideRequestInput: {
      /** @description Opaque identifier */
      fileId: string;
      profile: components['schemas']['DeviceProfileInput'];
      audioStreamIndex?: number;
      subtitleStreamIndex?: number;
      /** @default 0 */
      startPositionMs: number;
    };
    /** @enum {string} */
    PlaybackMethodInput: 'direct' | 'remux' | 'transcode';
    PlaybackDecisionInput: {
      method: components['schemas']['PlaybackMethodInput'];
      /** @description Relative URL of the media or HLS master playlist */
      url: string;
      sessionId: string | null;
      reason: string;
      subtitleUrls: {
        streamIndex: number;
        language: string | null;
        url: string;
      }[];
    };
    ProgressUpdateRequestInput: {
      /** @description Opaque identifier */
      itemId: string;
      positionMs: number;
      durationMs: number;
    };
    HealthResponseInput: {
      /** @constant */
      status: 'ok';
      version: string;
      time: string;
    };
    /** @enum {string} */
    LibraryKind: 'movie' | 'tv' | 'anime';
    /** @enum {string} */
    ItemKind: 'movie' | 'show' | 'season' | 'episode';
    ErrorResponse: {
      statusCode: number;
      error: string;
      message: string;
    };
    Profile: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      isAdmin: boolean;
      avatarColor: string;
    };
    /** @description True until the first admin profile exists */
    SetupStatus: {
      needsSetup: boolean;
    };
    SetupRequest: {
      name: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
    };
    LoginRequest: {
      /** @description Opaque identifier */
      profileId: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
      deviceName: string;
    };
    LoginResponse: {
      token: string;
      profile: components['schemas']['Profile'];
    };
    Session: {
      /** @description Opaque identifier */
      id: string;
      deviceName: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      lastSeenAt: string;
      current: boolean;
    };
    Library: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      kind: components['schemas']['LibraryKind'];
      paths: string[];
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      lastScannedAt: string | null;
    };
    CreateLibraryRequest: {
      name: string;
      kind: components['schemas']['LibraryKind'];
      paths: string[];
    };
    ScanStatus: {
      /** @description Opaque identifier */
      libraryId: string;
      /** @enum {string} */
      state: 'idle' | 'running';
      filesSeen: number;
      filesChanged: number;
      filesMissing: number;
      filesProbed: number;
      /** @description Files ffprobe could not read */
      filesFailed: number;
      /** @description Files linked to a movie or episode this scan */
      itemsLinked: number;
      startedAt: string | null;
    };
    ProgressState: {
      positionMs: number;
      durationMs: number;
      watched: boolean;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      updatedAt: string;
    };
    ItemSummary: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKind'];
      libraryKind: components['schemas']['LibraryKind'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressState'] | null;
    };
    StreamInfo: {
      index: number;
      /** @enum {string} */
      type: 'video' | 'audio' | 'subtitle';
      codec: string;
      language: string | null;
      title: string | null;
      isDefault: boolean;
      isForced: boolean;
      width: number | null;
      height: number | null;
      channels: number | null;
    };
    MediaFile: {
      /** @description Opaque identifier */
      id: string;
      fileName: string;
      sizeBytes: number;
      container: string;
      durationMs: number;
      bitrate: number | null;
      streams: components['schemas']['StreamInfo'][];
    };
    ItemDetail: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKind'];
      libraryKind: components['schemas']['LibraryKind'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressState'] | null;
      overview: string | null;
      tagline: string | null;
      genres: string[];
      rating: number | null;
      airDate: string | null;
      runtimeMs: number | null;
      tmdbId: number | null;
      anilistId: number | null;
      files: components['schemas']['MediaFile'][];
      /** @description Seasons of a show, episodes of a season */
      children: components['schemas']['ItemSummary'][];
    };
    FixMatchRequest: {
      tmdbId?: number;
      anilistId?: number;
      /** @description Anime only: shift when mapping absolute episodes onto TMDB seasons */
      seasonOffset?: number;
    };
    DeviceProfile: {
      name: string;
      /** @description e.g. mp4, mkv, webm */
      containers: string[];
      /** @description e.g. h264, hevc, vp9, av1 */
      videoCodecs: string[];
      /** @description e.g. aac, ac3, eac3, opus, flac */
      audioCodecs: string[];
      maxWidth: number | null;
      /** @description bits per second */
      maxBitrate: number | null;
      /** @enum {string} */
      hlsSegmentContainer: 'ts' | 'fmp4';
    };
    PlaybackDecideRequest: {
      /** @description Opaque identifier */
      fileId: string;
      profile: components['schemas']['DeviceProfile'];
      audioStreamIndex?: number;
      subtitleStreamIndex?: number;
      /** @default 0 */
      startPositionMs: number;
    };
    /** @enum {string} */
    PlaybackMethod: 'direct' | 'remux' | 'transcode';
    PlaybackDecision: {
      method: components['schemas']['PlaybackMethod'];
      /** @description Relative URL of the media or HLS master playlist */
      url: string;
      sessionId: string | null;
      reason: string;
      subtitleUrls: {
        streamIndex: number;
        language: string | null;
        url: string;
      }[];
    };
    ProgressUpdateRequest: {
      /** @description Opaque identifier */
      itemId: string;
      positionMs: number;
      durationMs: number;
    };
    HealthResponse: {
      /** @constant */
      status: 'ok';
      version: string;
      time: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
