/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponseInput: {
      /** @constant */
      status: 'ok';
      version: string;
      time: string;
    };
    /** @enum {string} */
    LibraryKindInput: 'movie' | 'tv' | 'anime';
    /** @enum {string} */
    ItemKindInput: 'movie' | 'show' | 'season' | 'episode';
    ErrorResponseInput: {
      statusCode: number;
      error: string;
      message: string;
    };
    ProfileInput: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      isAdmin: boolean;
      avatarColor: string;
    };
    /** @description True until the first admin profile exists */
    SetupStatusInput: {
      needsSetup: boolean;
    };
    SetupRequestInput: {
      name: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
    };
    LoginRequestInput: {
      /** @description Opaque identifier */
      profileId: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
      deviceName: string;
    };
    LoginResponseInput: {
      token: string;
      profile: components['schemas']['ProfileInput'];
    };
    SessionInput: {
      /** @description Opaque identifier */
      id: string;
      deviceName: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      lastSeenAt: string;
      current: boolean;
    };
    LibraryInput: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      kind: components['schemas']['LibraryKindInput'];
      paths: string[];
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      lastScannedAt: string | null;
    };
    CreateLibraryRequestInput: {
      name: string;
      kind: components['schemas']['LibraryKindInput'];
      paths: string[];
    };
    ScanStatusInput: {
      /** @description Opaque identifier */
      libraryId: string;
      /** @enum {string} */
      state: 'idle' | 'running';
      filesSeen: number;
      filesChanged: number;
      startedAt: string | null;
    };
    ProgressStateInput: {
      positionMs: number;
      durationMs: number;
      watched: boolean;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      updatedAt: string;
    };
    ItemSummaryInput: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKindInput'];
      libraryKind: components['schemas']['LibraryKindInput'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressStateInput'] | null;
    };
    StreamInfoInput: {
      index: number;
      /** @enum {string} */
      type: 'video' | 'audio' | 'subtitle';
      codec: string;
      language: string | null;
      title: string | null;
      isDefault: boolean;
      isForced: boolean;
      width: number | null;
      height: number | null;
      channels: number | null;
    };
    MediaFileInput: {
      /** @description Opaque identifier */
      id: string;
      fileName: string;
      sizeBytes: number;
      container: string;
      durationMs: number;
      bitrate: number | null;
      streams: components['schemas']['StreamInfoInput'][];
    };
    ItemDetailInput: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKindInput'];
      libraryKind: components['schemas']['LibraryKindInput'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressStateInput'] | null;
      overview: string | null;
      tagline: string | null;
      genres: string[];
      rating: number | null;
      airDate: string | null;
      runtimeMs: number | null;
      tmdbId: number | null;
      anilistId: number | null;
      files: components['schemas']['MediaFileInput'][];
      /** @description Seasons of a show, episodes of a season */
      children: components['schemas']['ItemSummaryInput'][];
    };
    FixMatchRequestInput: {
      tmdbId?: number;
      anilistId?: number;
      /** @description Anime only: shift when mapping absolute episodes onto TMDB seasons */
      seasonOffset?: number;
    };
    DeviceProfileInput: {
      name: string;
      /** @description e.g. mp4, mkv, webm */
      containers: string[];
      /** @description e.g. h264, hevc, vp9, av1 */
      videoCodecs: string[];
      /** @description e.g. aac, ac3, eac3, opus, flac */
      audioCodecs: string[];
      maxWidth: number | null;
      /** @description bits per second */
      maxBitrate: number | null;
      /** @enum {string} */
      hlsSegmentContainer: 'ts' | 'fmp4';
    };
    PlaybackDecideRequestInput: {
      /** @description Opaque identifier */
      fileId: string;
      profile: components['schemas']['DeviceProfileInput'];
      audioStreamIndex?: number;
      subtitleStreamIndex?: number;
      /** @default 0 */
      startPositionMs: number;
    };
    /** @enum {string} */
    PlaybackMethodInput: 'direct' | 'remux' | 'transcode';
    PlaybackDecisionInput: {
      method: components['schemas']['PlaybackMethodInput'];
      /** @description Relative URL of the media or HLS master playlist */
      url: string;
      sessionId: string | null;
      reason: string;
      subtitleUrls: {
        streamIndex: number;
        language: string | null;
        url: string;
      }[];
    };
    ProgressUpdateRequestInput: {
      /** @description Opaque identifier */
      itemId: string;
      positionMs: number;
      durationMs: number;
    };
    HealthResponse: {
      /** @constant */
      status: 'ok';
      version: string;
      time: string;
    };
    /** @enum {string} */
    LibraryKind: 'movie' | 'tv' | 'anime';
    /** @enum {string} */
    ItemKind: 'movie' | 'show' | 'season' | 'episode';
    ErrorResponse: {
      statusCode: number;
      error: string;
      message: string;
    };
    Profile: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      isAdmin: boolean;
      avatarColor: string;
    };
    /** @description True until the first admin profile exists */
    SetupStatus: {
      needsSetup: boolean;
    };
    SetupRequest: {
      name: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
    };
    LoginRequest: {
      /** @description Opaque identifier */
      profileId: string;
      /** @description Numeric PIN, 4 to 6 digits */
      pin: string;
      deviceName: string;
    };
    LoginResponse: {
      token: string;
      profile: components['schemas']['Profile'];
    };
    Session: {
      /** @description Opaque identifier */
      id: string;
      deviceName: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      lastSeenAt: string;
      current: boolean;
    };
    Library: {
      /** @description Opaque identifier */
      id: string;
      name: string;
      kind: components['schemas']['LibraryKind'];
      paths: string[];
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      createdAt: string;
      lastScannedAt: string | null;
    };
    CreateLibraryRequest: {
      name: string;
      kind: components['schemas']['LibraryKind'];
      paths: string[];
    };
    ScanStatus: {
      /** @description Opaque identifier */
      libraryId: string;
      /** @enum {string} */
      state: 'idle' | 'running';
      filesSeen: number;
      filesChanged: number;
      startedAt: string | null;
    };
    ProgressState: {
      positionMs: number;
      durationMs: number;
      watched: boolean;
      /**
       * Format: date-time
       * @description ISO 8601 UTC timestamp
       */
      updatedAt: string;
    };
    ItemSummary: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKind'];
      libraryKind: components['schemas']['LibraryKind'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressState'] | null;
    };
    StreamInfo: {
      index: number;
      /** @enum {string} */
      type: 'video' | 'audio' | 'subtitle';
      codec: string;
      language: string | null;
      title: string | null;
      isDefault: boolean;
      isForced: boolean;
      width: number | null;
      height: number | null;
      channels: number | null;
    };
    MediaFile: {
      /** @description Opaque identifier */
      id: string;
      fileName: string;
      sizeBytes: number;
      container: string;
      durationMs: number;
      bitrate: number | null;
      streams: components['schemas']['StreamInfo'][];
    };
    ItemDetail: {
      /** @description Opaque identifier */
      id: string;
      kind: components['schemas']['ItemKind'];
      libraryKind: components['schemas']['LibraryKind'];
      title: string;
      year: number | null;
      posterKey: string | null;
      backdropKey: string | null;
      seasonNumber: number | null;
      episodeNumber: number | null;
      showTitle: string | null;
      needsReview: boolean;
      progress: components['schemas']['ProgressState'] | null;
      overview: string | null;
      tagline: string | null;
      genres: string[];
      rating: number | null;
      airDate: string | null;
      runtimeMs: number | null;
      tmdbId: number | null;
      anilistId: number | null;
      files: components['schemas']['MediaFile'][];
      /** @description Seasons of a show, episodes of a season */
      children: components['schemas']['ItemSummary'][];
    };
    FixMatchRequest: {
      tmdbId?: number;
      anilistId?: number;
      /** @description Anime only: shift when mapping absolute episodes onto TMDB seasons */
      seasonOffset?: number;
    };
    DeviceProfile: {
      name: string;
      /** @description e.g. mp4, mkv, webm */
      containers: string[];
      /** @description e.g. h264, hevc, vp9, av1 */
      videoCodecs: string[];
      /** @description e.g. aac, ac3, eac3, opus, flac */
      audioCodecs: string[];
      maxWidth: number | null;
      /** @description bits per second */
      maxBitrate: number | null;
      /** @enum {string} */
      hlsSegmentContainer: 'ts' | 'fmp4';
    };
    PlaybackDecideRequest: {
      /** @description Opaque identifier */
      fileId: string;
      profile: components['schemas']['DeviceProfile'];
      audioStreamIndex?: number;
      subtitleStreamIndex?: number;
      /** @default 0 */
      startPositionMs: number;
    };
    /** @enum {string} */
    PlaybackMethod: 'direct' | 'remux' | 'transcode';
    PlaybackDecision: {
      method: components['schemas']['PlaybackMethod'];
      /** @description Relative URL of the media or HLS master playlist */
      url: string;
      sessionId: string | null;
      reason: string;
      subtitleUrls: {
        streamIndex: number;
        language: string | null;
        url: string;
      }[];
    };
    ProgressUpdateRequest: {
      /** @description Opaque identifier */
      itemId: string;
      positionMs: number;
      durationMs: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
